(eval-after-load 'efar
  '(progn
     (define-key efar-mode-map (kbd "<up>") 'efar-do-move-up)
     (define-key efar-mode-map (kbd "<down>") 'efar-do-move-down)
     (define-key efar-mode-map (kbd "<left>") 'efar-do-move-left)
     (define-key efar-mode-map (kbd "<prior>") 'efar-do-move-left)
     (define-key efar-mode-map (kbd "<right>") 'efar-do-move-right)
     (define-key efar-mode-map (kbd "<next>") 'efar-do-move-right)
     (define-key efar-mode-map (kbd "<home>") 'efar-do-move-home)
     (define-key efar-mode-map (kbd "<end>") 'efar-do-move-end)
     (define-key efar-mode-map (kbd "<C-left>") 'efar-do-move-home)
     (define-key efar-mode-map (kbd "<C-right>") 'efar-do-move-end)
     (define-key efar-mode-map (kbd "RET") 'efar-do-enter-directory)
     (define-key efar-mode-map (kbd "C-<up>") 'efar-do-enter-parent)
     (define-key efar-mode-map (kbd "C-c c d") 'efar-do-change-directory)
     (define-key efar-mode-map (kbd "TAB") 'efar-do-switch-to-other-panel)
     (define-key efar-mode-map (kbd "C-c TAB") 'efar-do-open-dir-other-panel)
     (define-key efar-mode-map (kbd "<f4>") 'efar-do-edit-file)
     (define-key efar-mode-map (kbd "<M-f4>") 'efar-do-open-file-in-external-app)
     (define-key efar-mode-map (kbd "<f3>") 'efar-do-read-file)
     (define-key efar-mode-map (kbd "<insert>") 'efar-do-mark-file)
     (define-key efar-mode-map (kbd "<C-insert>") 'efar-do-unmark-all)
     (define-key efar-mode-map (kbd "<C-M-insert>") 'efar-do-mark-all)
     (define-key efar-mode-map (kbd "<f5>") 'efar-do-copy)
     (define-key efar-mode-map (kbd "<f6>") 'efar-do-rename)
     (define-key efar-mode-map (kbd "<f7>") 'efar-do-make-dir)
     (define-key efar-mode-map (kbd "<f8>") 'efar-do-delete)
     (define-key efar-mode-map (kbd "<M-up>") 'efar-do-scroll-other-window-up)
     (define-key efar-mode-map (kbd "<M-down>") 'efar-do-scroll-other-window-down)
     (define-key efar-mode-map (kbd "S-C-<left>") 'efar-do-move-splitter-left)
     (define-key efar-mode-map (kbd "S-C-<right>") 'efar-do-move-splitter-right)
     (define-key efar-mode-map (kbd "S-C-<down>") 'efar-do-move-splitter-center)
     (define-key efar-mode-map (kbd "C-c f m") 'efar-do-set-file-modes)
     (define-key efar-mode-map (kbd "C-c f d") 'efar-do-show-disk-selector)
     (define-key efar-mode-map (kbd "C-c f s") 'efar-do-change-sorting)
     (define-key efar-mode-map (kbd "C-c f f") 'efar-do-filter-files)
     (define-key efar-mode-map (kbd "C-c v M") 'efar-do-change-mode)
     (define-key efar-mode-map (kbd "C-c v +") 'efar-do-increase-column-number)
     (define-key efar-mode-map (kbd "C-c v -") 'efar-do-decrease-column-number)
     (define-key efar-mode-map (kbd "C-c v m") 'efar-do-change-file-display-mode)
     (define-key efar-mode-map (kbd "C-c c p") 'efar-do-copy-file-path)
     (define-key efar-mode-map (kbd "C-c c e") 'efar-do-ediff-files)
     (define-key efar-mode-map (kbd "C-c c s") 'efar-do-file-stat)
     (define-key efar-mode-map (kbd "C-c c o") 'efar-do-open-shell)
     (define-key efar-mode-map (kbd "M-RET") 'efar-do-send-to-shell)
     (define-key efar-mode-map (kbd "C-c c b") 'efar-do-show-bookmarks)
     (define-key efar-mode-map (kbd "C-c c B") 'efar-do-add-bookmark)
     (define-key efar-mode-map (kbd "C-c c h") 'efar-do-show-directory-history)
     (define-key efar-mode-map (kbd "<C-M-up>") 'efar-do-directory-history-previous)
     (define-key efar-mode-map (kbd "<C-M-down>") 'efar-do-directory-history-next)
     (define-key efar-mode-map (kbd "C-c c f") 'efar-do-show-file-history)
     (define-key efar-mode-map (kbd "C-c c n") 'efar-do-run-batch-rename)
     (define-key efar-mode-map (kbd "C-c c r") 'efar-do-run-batch-replace)
     (define-key efar-mode-map (kbd "C-c <M-f7>") 'efar-do-start-search)
     (define-key efar-mode-map (kbd "C-c <S-f7>") 'efar-do-show-search-results)
     (define-key efar-mode-map (kbd "C-c <C-f7>") 'efar-do-show-search-history)
     (define-key efar-mode-map (kbd "C-c <C-M-f7>") 'efar-do-show-search-results-in-buffer)
     (define-key efar-mode-map (kbd "C-c <M-f6>") 'efar-do-start-directory-comparison)
     (define-key efar-mode-map (kbd "C-c <S-f6>") 'efar-do-show-directory-comparison-results)
     (define-key efar-mode-map (kbd "C-c <C-M-f6>") 'efar-do-show-directory-comparison-results-in-buffer)
     (define-key efar-mode-map (kbd "C-c <f6> a") 'efar-do-directory-comparison-toggle-changed-only)
     (define-key efar-mode-map (kbd "C-c <f6> s") 'efar-do-directory-comparison-toggle-size)
     (define-key efar-mode-map (kbd "C-c <f6> h") 'efar-do-directory-comparison-toggle-checksum)
     (define-key efar-mode-map (kbd "C-c <f6> o") 'efar-do-directory-comparison-toggle-owner)
     (define-key efar-mode-map (kbd "C-c <f6> g") 'efar-do-directory-comparison-toggle-group)
     (define-key efar-mode-map (kbd "C-c <f6> m") 'efar-do-directory-comparison-toggle-modes)
     (define-key efar-mode-map (kbd "C-c c m") 'efar-do-show-mode-selector)
     (define-key efar-mode-map (kbd "C-c ?") 'efar-do-show-help)
     (define-key efar-mode-map (kbd "C-t") 'efar-do-change-theme)
     (define-key efar-mode-map (kbd "C-g") 'efar-do-abort)
     (define-key efar-mode-map (kbd "<f12> <f12>") 'efar-do-reinit)
     (define-key efar-mode-map (kbd "C-n") 'efar-do-suggest-hint)))
